"""test.

Revision ID: 25824207072c
Revises: e3b06cfd020c
Create Date: 2021-04-14 22:14:01.363845
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "25824207072c"
down_revision = "e3b06cfd020c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_html",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False, comment="HTML content"),
        sa.Column("origin", sa.Text(), nullable=False, comment="Download URL"),
        sa.Column("uploaded_by_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"], ["user.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_html")
    # ### end Alembic commands ###
