"""html_type.

Revision ID: 744d2555f68a
Revises: 25824207072c
Create Date: 2021-04-14 22:27:10.369500
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "744d2555f68a"
down_revision = "25824207072c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "raw_html",
        sa.Column(
            "type",
            sa.Enum(
                "summary",
                "running_attempt",
                "finished_attempt",
                "all_course_tasks",
                "all_courses",
                name="htmltype",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_html", "type")
    # ### end Alembic commands ###
