"""base.

Revision ID: e3b06cfd020c
Revises:
Create Date: 2020-05-08 15:32:24.653785
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e3b06cfd020c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
